[package]
authors = ['Anonymous']
edition = '2018'
name = 'litentry-pallet'
version = "0.0.1"
license = "Unlicense"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME pallet template"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.2.0", default-features = false, features = ["derive"] }
safe-mix = { default-features = false, version = '1.0.0' }
sp-runtime = { version = "2.0.0-alpha.5", default-features = false, path = "../../../../primitives/runtime" }
sp-io = { version = "2.0.0-alpha.5", default-features = false, path = "../../../../primitives/io" }
sp-core = { version = "2.0.0-alpha.5", default-features = false, path = "../../../../primitives/core" }
balances = { version = "2.0.0-alpha.5", default-features = false, package = "pallet-balances", path = "../../../../frame/balances" }
litentry-utils = {version= "0.1.0", default-features = false, path="../../utils"}

[dev-dependencies]
randomness-collective-flip = { version = "2.0.0-alpha.5", default-features = false, package = "pallet-randomness-collective-flip", path = "../../../../frame/randomness-collective-flip" }

[dependencies.frame-support]
default-features = false
version = "2.0.0-alpha.5"
path = "../../../../frame/support"

[dependencies.frame-system]
default-features = false
version = "2.0.0-alpha.5"
path = "../../../../frame/system"

[dev-dependencies.sp-io]
default-features = false
version = "2.0.0-alpha.5"
path = "../../../../primitives/io"


[features]
default = ['std']
std = [
	'codec/std',
	'frame-support/std',
	'safe-mix/std',
	"sp-runtime/std",
	'frame-system/std',
		"sp-io/std",
		'sp-core/std',
		'balances/std',
		'litentry-utils/std',
		'randomness-collective-flip/std'
]
