[package]
authors = ['Anonymous']
edition = '2018'
name = 'litentry-pallet'
version = "0.0.1"
license = "Unlicense"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME pallet template"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.2.0", default-features = false, features = ["derive"] }
sp-std = { version = "2.0.0-dev", default-features = false, path = "../../../../primitives/std" }
pallet-balances = { version = "2.0.0-dev", default-features = false, package = "pallet-balances", path = "../../../../frame/balances" }
litentry-utils = {version= "0.1.0", default-features = false, path="../../utils"}

[dev-dependencies]
randomness-collective-flip = { version = "2.0.0-dev", default-features = false, package = "pallet-randomness-collective-flip", path = "../../../../frame/randomness-collective-flip" }

[dependencies.frame-support]
default-features = false
version = "2.0.0-dev"
path = "../../../../frame/support"

[dependencies.frame-system]
default-features = false
version = "2.0.0-dev"
path = "../../../../frame/system"
[dev-dependencies.sp-core]
default-features = false
version = "2.0.0-dev"
path = "../../../../primitives/core"

[dev-dependencies.sp-io]
default-features = false
version = "2.0.0-dev"
path = "../../../../primitives/io"

[dev-dependencies.sp-runtime]
default-features = false
version = "2.0.0-dev"
path = "../../../../primitives/runtime"



[features]
default = ['std']
std = [
	'codec/std',
	'frame-support/std',
	"sp-runtime/std",
	'frame-system/std',
		"sp-io/std",
		"sp-std/std",
		'sp-core/std',
		'pallet-balances/std',
		'litentry-utils/std',
		'randomness-collective-flip/std'
]
